github/homebrew-bootstrap

cmd/brew-bootstrap-rbenv-ruby

`echo` and newlines do not play easily so just make multiple echos for each newline. Also, tweak the wording to be more easily readable.

Improve debugging output.

---

cmd/brew-setup-nginx-conf

CC @ross @scottjg
Closes https://github.com/github/github/issues/48141.

brew-setup-nginx-conf: fix --root without brew.

---

cmd/brew-bootstrap-rbenv-ruby

The link would be helpful when the first error pops up :)

add reference to rbenv setup

---

cmd/brew-setup-nginx-conf

cc @MikeMcQuaid 
Refs github/friction#19.

nginx: Uninstall pf and install launch_socket_server

---

cmd/brew-vendor-gem

This is imported from github/github, with a few tweaks, to make it easier to use with other projects.
cc @technicalpickles, @MikeMcQuaid

Import vendor-gem from github/github

---

Formula/elasticsearch@1.7.rb

Temporarily import elasticsearch 1.7

---

cmd/brew-report-issue.rb
cmd/brew-setup-nginx-conf

- Fix various RuboCop warnings
- Avoid using non-`HOMEBREW_` environment variables as they will be shortly filtered out by Homebrew itself.
- Remove Boxen compatibility layer.
CC @mistydemeo @github/dx for review

Various cleanups

---

README.md

`brew-setup-nginx-conf` => `brew-setup-nginx-conf.rb`

Fix link to brew-setup-nginx-conf

---

Formula/elasticsearch@1.7.rb

Fix `brew style` and `odeprecated` warnings.

elasticsearch@1.7: fix style.

---

cmd/brew-setup-nginx-conf.rb

Since Homebrew filters environment variables, it isn't safe to pass through values that way. This adds an extra arugment to `brew setup-nginx-conf` to allow extra variables to be specified on the commandline instead. The format is:
```
--extra-val=name=value
```
This argument is repeatable; `--extra-val` can be repeated as many times as desired.
This was inspired by a project which attempted to use environment variables to specify values in their nginx conf `.erb` files; their variable was being stripped out. `brew setup-nginx-conf app . config/dev/nginx.conf.erb --extra-val=rails_root=/path/to/root` works via this change.

brew setup-nginx-conf: allow extra values to be specified

---

Casks/zulu11.rb
cmd/brew-bootstrap-jenv-java

The `zulu11` package is taken from this other PR of mine: https://github.com/Homebrew/homebrew-cask/pull/54071 I'll update it here if that package is changed before it's merged.

Add zulu11 package

---

cmd/brew-setup-nginx-conf.rb

Typod this, whoops. CC @mistydemeo

cmd/brew-setup-nginx-conf: fix brew cleanup args.

---

Formula/kind.rb

kind 0.3.0

---

Formula/kustomize@3.1.rb

This adds a new formula for Kustomize 3.1.0. 
/cc @jnewland @mistydemeo

Add formula for kustomize 3.1

---

.github/workflows/ci.yml
.travis.yml

This currently just maintains the existing logic, but we can look at building out more features later.

Switch Travis to Actions

---

Formula/kubectl@1.14.rb

Mostly taken from the upstream formula 
/cc @mistydemeo

Adds kubectl 1.14 formula

---

cmd/brew-upgrade-mysql

Change the wording on completion to be consistent with script/bootstrap (where this is run from)
Companion to https://github.com/github/github/pull/172371

brew-upgrade-mysql: tweak wording.

---

cmd/brew-macos-vscode-codespaces

It's more useful for this to be a standalone command here to remove the dependency on github/github.

brew-macos-vscode-codespaces: import from github/github.

---

README.md

Add new scripts and make general updates.

README: various updates.

---

README.md

Looks like it was copy & pasted from upgrade-mysql

Fix link to vendor-gem
