.travis.yml, LICENSE.txt, README.md, cmd/brew-report-issue.rb, cmd/brew-setup-nginx-conf
This script has two modes: filing issues and closing them.
When filing issues the body is piped in over STDIN and the issue title and repository specified on the command-line. To avoid noise: this should probably only be used on dedicated repositories for these issues as they may be autoposted frequently.
When closing issues all issues filed by the user will be closed on the repository and a comment with the success state will be posted to each of the issues.
GitHub API credentials are extracted based on access to HTTPS GitHub repositories.
This tool is designed to behave similarly to how Boxen did and will be used by projects for autoposting issues.
CC @github/friction @github/workflow-tools
=> brew-report-issue: report/close project issues.

cmd/brew-report-issue.rb
Previously I was using a filter that was defined on another endpoint. Have verified this behaves as expected locally (thanks @mhp for help here).
=> brew-report-issue: fix user issue filtering.

cmd/brew-report-issue.rb
`git credential fill` prompts for but does not save any credentials.
Instead of asking for them every time look for a credential helper, ask for the credentials once, store them and invalidate them if authentication failed. For edge-cases: tell people to use Strap which sets this all up for them instead.
CC @scottjg @nakajima
=> brew-report-issue: setup Git credentials.

cmd/brew-report-issue.rb
@peff pointed out to me that you can use `git credential approve` to simplify some of this code.
CC @peff to see if this is what you had in mind.
Closes #4.
=> brew-report-issue: cleanup `git credential` usage.

cmd/brew-report-issue.rb
Firstly, allow errors to be outputted to aid in debugging.
Secondly, unset `RUBYLIB` and `RUBYOPT` in case they are set to invalid values for the system Ruby which Boxen uses for its credential handler.
Thanks to @amosie for letting me debug this on her machine!
=> brew-report-issue: fix Boxen credential handler.

cmd/brew-report-issue.rb
Point people towards the fact that it needs to be an access token rather than password and these can be set by running Strap.
CC @github/friction and thanks to @davidcelis for the suggestion in https://github.com/github/github-bootstrap-failures/issues/26
=> brew-report-issue: provide more help on a 401.

cmd/brew-bootstrap-nodenv-node, cmd/brew-bootstrap-rbenv-ruby
Addresses an issue where @nixpad added this before the end of her `.bash_profile` and as a result the `$PATH` wasn't set correct.
@nixpad would this message have made it clearer? If not, do you have a suggestion of what might? Thanks!
CC @github/friction for :thought_balloon:.
=> Tweak rbenv/nodenv error messaging.

cmd/brew-report-issue.rb
Sometimes the Git credentials username is actually just a token. In this case we need to look to the environment to find a token or configuration setting there instead.
An example of this issue is https://github.com/github/github-bootstrap-failures/issues/80.
CC @github/friction
=> brew-report-issue: fix username detection.

cmd/brew-report-issue.rb
Check username strings for emptiness rather than for nil to avoid reporting issues with empty usernames in some cases.
=> brew-report-issue: try harder to avoid empty user.

ruby-definitions/2.0.0-github, ruby-definitions/2.1.0-github, ruby-definitions/2.1.1-github, ruby-definitions/2.1.2-github, ruby-definitions/2.1.4-github, ruby-definitions/2.1.5-github, ruby-definitions/2.1.6-github, ruby-definitions/2.1.7-github
Hey! @mikemcquaid, is this of interest to you? Was upgrading my [ruby-build-github specs](https://github.com/parkr/ruby-build-github/commit/b6f88076ec3a3aed571e2db4e567decb4dce0656) and figured I would suggest it here as well.
Thanks!
=> Upgrade OpenSSL to v1.0.2g

cmd/brew-bootstrap-rbenv-ruby
Otherwise a `bundle` from outside rbenv that comes first in the PATH will satisfy the check, e.g. `/usr/bin/bundle`
cc @mikemcquaid
=> Look up bundler within the active ruby

cmd/brew-bootstrap-rbenv-ruby
Even if the correct `ruby` is installed we've got to make sure we check that the relevant `rbenv init` call has been run.
CC @mistydemeo and @tomkrouper who hit this.
=> brew-bootstrap-rbenv-ruby: always check rbenv init

cmd/brew-bootstrap-nodenv-node, cmd/brew-bootstrap-rbenv-ruby
Instead of having a single generic warning, sniff the value of `$SHELL` and provide a specific warning based on that. This should help some of the confusion Mike mentioned in #18. Supports `sh`/`bash`, `zsh`, and `fish`; `tcsh`-using cowgirls are on their own.
cc @mikemcquaid, @ErinCall
=> Add per-shell setup instructions

cmd/brew-bootstrap-nodenv-node
The functions warn_sh, warn_zsh and warn_fish were renamed to abort_for_sh, abort_for_zsh and abort_for_fish, but calls to those functions were not renamed.  This renames this calls.
=> Update calls to abort_for_* functions

cmd/brew-report-issue.rb
When looking for a Git credential helper instead of demanding it is set in `~/.gitconfig` also allow it to be set at a project or system level (such as Apple's Git now does).
=> brew-report-issue: check global Git configuration.

cmd/brew-setup-nginx-conf
This [mirrors what github/github does](https://github.com/github/github/blob/0650820e9d68f97145fc0474d1ddb0270a4198e3/script/osx-setup#L71-L72) and avoids accidentally creating e.g. `/etc/resolver/resolver`.
CC @bhuga @snh @josh 
Closes https://github.com/github/developer-experience/issues/206.
=> setup-nginx-conf: remove old /etc/resolver.

cmd/brew-setup-nginx-conf
As far as I know, everything's using ports now, rather than sockets. By getting rid of launch_socket_server we can avoid needing sudo in the normal case.
Needing sudo has been a pain for me because of a handful of script/test files that call script/bootstrap which calls setup-nginx-conf. Needing sudo to run tests is silly.
=> Drop launch_socket_server from setup-nginx-conf

cmd/brew-setup-nginx-conf
Show `setup` instead of `generate` when aborting.
=> Fix cmd name when no params given

cmd/brew-bootstrap-rbenv-ruby
This error message can also mean that `ruby-build` is out of date, so I find it helpful to mention that in the message.
cc @MikeMcQuaid
=> bootstrap-rbenv-ruby: reword "cannot find definition" message slightly

cmd/brew-setup-nginx-conf.rb
This fixes a problem that #43 seems to have triggered for myself and @phantomdata, whereby no project that uses `brew setup-nginx-conf` in its bootstrap can successfully interpolate the ERB file. I tested this with three separate projects (halp, githubber.tv and docsotron), and all three returned similar errors:
```
Error: undefined local variable or method `root' for main:Object
(erb):2:in `<main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/erb.rb:864:in `eval'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/erb.rb:864:in `result'
/usr/local/Homebrew/Library/Taps/github/homebrew-bootstrap/cmd/brew-setup-nginx-conf.rb:29:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rub …
```
=> Fix ERB interpolation in brew-setup-nginx-conf

cmd/brew-upgrade-mysql
For our internal applications we need to move applications that use MySQL 5.6 to use 5.7.
This step follows the following logic from @ggunson 
> If mysql5.6 is installed:
>
> shutdown mysql
uninstall 5.6, install 5.7
modify the my.cnf file with new changes
start up mysql
run mysql_upgrade script
restart mysql
> If mysql5.7 is installed:
>
> shutdown mysql
modify the my.cnf file with the new changes
start up mysql
run mysql_upgrade script
restart mysql
Instead of modifying the `my.cnf` file I'm just backing up the existing one to `my.cnf.github` and replacing it with the following code
```
[mysqld]
innodb_strict_mode=OFF
optimizer_switch='index_merge_intersection=OFF'
query_cache_size=0
sql_mode=NO_ENGINE_SUBSTITUTION
```
I'm sure I've botched up the scripting so any guidance would be 💯
=> Add command to upgrade homebrew MySQL 5.6 to 5.7

cmd/brew-upgrade-mysql
Ran into an issue where the `set +e` on `mysql_upgrade` caused the script to die from `mysql_upgrade` exiting 2 because my MySQL was already up to date. This silences the `mysql_upgrade` output and treats it as a success if it exits for that reason, otherwise it lets the failure bubble up.
=> upgrade-mysql: don't die if mysql_upgrade has already been run

README.md, cmd/brew-upgrade-mysql
The original iteration of this script was a bit rushed so it ended up with a few undesirable features, like restarting every run. @ggunson started work on this, but I asked if I could take a stab at it, so she kindly allowed me to play around with this. This should handle upgrades smoothly and once everything is set not restart anymore.
I've tested this to
* upgrade from 5.6 to 5.7
* upgrade from 5.7.20 to 5.7.21 (with an optional command line)
It works as expected. In addition I added a link to the readme as requested by @MikeMcQuaid in @ggunson's [original PR](https://github.com/github/homebrew-bootstrap/pull/51).
=> Rewrite brew-upgrade-mysql

cmd/brew-upgrade-mysql
This helps avoid trying to start mysql twice.
Ran into an issue with `Brewfile` having `restart => true` for mysql. I will attempt to find all of the occurrences of this, but if I miss any, this will ensure everything runs smoothly.
cc: @github/database-infrastructure, @mistydemeo
=> Restart MySQL instead of start

ruby-definitions/2.4-typedruby1
Addition for local bootstrap of 2.4-typedruby
cc: @charliesome @gnawhleinad @MikeMcQuaid
=> Add 2.4-typedruby definition

cmd/brew-bootstrap-rbenv-ruby
This resolves an inconsistency which would occur if `RBENV_VERSION` was exported, and also makes it possible to use that environment variable to specify the Ruby version to install.
If `RBENV_VERSION` is exported, the `rbenv version-name` check will respect that environment variable; however, the `RUBY_REQUESTED` check was hardcoded to use `rbenv local`, which only considers `.ruby-version`. This improves that check by using `RBENV_VERSION` if specified, and falls back to `.ruby-version` if not; that behaviour matches the fallback preference used by `rbenv version-name`.
=> bootstrap-rbenv-ruby: respect RBENV_VERSION

cmd/brew-upgrade-mysql
Seems that jq is not installed for everyone, so rather than putting that in a Brewfile on every repo that uses this, I'm manually installing this inside the script. If there is a better way, please let me know.
Note, https://github.com/github/github/blob/master/config/homebrew-bootstrap-version will need to be updated once this is merged.
cc: https://github.com/github/homebrew-bootstrap/issues/57
=> Ensure jq is installed

cmd/brew-upgrade-mysql
On my system, every bootstrap was stopping and starting MySQL:
```
hettg@rhettbook ~/github/github (master) $ script/bootstrap
Ruby build 0d9762bcc5 is up-to-date.
Checking macOS Homebrew dependencies ...
The Brewfile's dependencies are satisfied.
Checking that MySQL is up to date.
Upgrading version of MySQL to 5.7.21...
Stopping `mysql`... (might take a while)
==> Successfully stopped `mysql` (label: homebrew.mxcl.mysql)
Waiting for MySQL to shut down.... done
Updating Homebrew...
Error: mysql@5.7 5.7.21 already installed
==> Successfully started `mysql` (label: homebrew.mxcl.mysql)
Waiting for MySQL to be available.... done
MySQL is ready.
Using Rails 3.2...
Git build 74d5b78aaf is up-to-date.
babeld build 9737740b31 is up-to-date.
codeload build 25db46ca76 is up-to-date.
dgit-update …
```
=> Use most recent version for "current" mysql version check.

cmd/brew-upgrade-mysql
Homebrew has now shipped MySQL 8.0 as `mysql`, which has exposed a few bugs with the logic in this script. Namely:
* A few places start and stop `mysql` instead of `mysql@5.7`, assuming that they're equivalent, which they no longer are.
* The current/installed versions are looked up as `mysql` instead of `mysql@5.7`.
* We should no longer allow `mysql` to be considered the correct package.
I've tested, and this will safely migrate users to the versioned package.
=> Fix brew-upgrade-mysql for latest changes

cmd/brew-upgrade-mysql
I realized that this will fail if the user has multiple versions of `mysql` installed; this will happen if the user had `brew upgrade`d a few times without ever running `brew cleanup`. For example:
```
Uninstalling old version of MySQL... 
Error: mysql has multiple installed versions
```
=> upgrade-mysql: uninstall all obsolete MySQL packages

cmd/brew-upgrade-mysql
When using MySQL 5.7 and older on macOS, select(2) is used, which limits the number of file descriptors that can be used to FD_SETSIZE (1024). Unfortunately, MySQL is not very good at limiting its use of file descriptors, and it will happily use all of them on caches, preventing connections to the database for queries.
Since this is not a very useful state to be in, limit the number of files used for caching open descriptors to 100. This should be fine for a typical development environment, and ensures that sufficient connections can be made for queries to execute.
=> brew-upgrade-mysql: limit table_open_cache

cmd/brew-bootstrap-rbenv-ruby
As noted in #68, Bundler 2 doesn't install on Ruby versions below 2.3. We should detect that case and install a compatible bundler when appropriate.
Fixes #68.
=> bootstrap-rbenv-ruby: install older Bundler on < 2.3

cmd/brew-upgrade-mysql
I noticed an issue where this script bails out early in the process if MySQL isn't installed at all. The expected behaviour is that it should go ahead and install it if it's not present.
The problem is in `install_mysql`; the `grep` in the assignment to `current_mysql` would exit 1 if no `mysql` package is installed, and because the script is run `set -e`, the entire script would bail out. This change allows the function to continue even if `grep` finds nothing.
=> upgrade-mysql: fix when MySQL is not installed

cmd/brew-setup-nginx-conf.rb
`brew prune` has been deprecated and its replacement in Homebrew doesn't do what we were using it for - removing dangling symlinks from Homebrew's prefix without other side effects.
This reimplements a basic `brew prune`-alike that handles just any dangling Nginx server symlinks, which is what we wanted from it.
Fixes #71.
/cc @dbuskariol, @MikeMcQuaid
=> setup-ngninx-conf: replace `brew prune`

cmd/brew-setup-nginx-conf.rb
This was re-added as an alternative to the old `brew prune` on popular demand.
=> brew-setup-nginx-conf: use `brew cleanup --prune`.

Formula/kustomize@2.0.rb
This adds a formula for kustomize 2.0.3, since there are some incompatible changes in newer versions. Per Homebrew convention, I named the formula after the release branch, but the formula itself is 2.0.3.
I've installed it with a binary named `kustomize@2.0` so it can sit alongside newer versions; that avoids link conflicts, and hopefully makes testing of newer versions easier.
=> kustomize@2.0 2.0.3

Formula/kind.rb
This PR adds Hive@2 and Hadoop@2 formulas to be able to setup our local development environment on Mac OS X as we need to interact with Hive 2.3.2.
/cc @github/data-engineering
=> Add Hive@2 and Hadoop@2 formulas

cmd/brew-upgrade-mysql
There was a new revision of mysql@5.7 built which added an `_1` to the mysql version number. Because of this everytime someone used the brew-upgrade-mysql script, it would attempt to unnecessarily upgrade mysql. This change fixes that logic that caused this.
fixes: https://github.com/github/homebrew-bootstrap/issues/81
cc: @github/database-infrastructure
=> Update the mysql version check to use `brew outdated`.

cmd/brew-bootstrap-rbenv-ruby
ruby-build itself has workarounds for OpenSSL now, and with potentially multiple versions needed this workaround doesn't always work. We have better solutions now.
=> bootstrap-rbenv-ruby: stop using Homebrew openssl

Formula/elasticsearch@2.4.rb
This adds a formula for `elasticsearch@2.4`, which was recently deleted from Homebrew core.
=> Import elasticsearch@2.4

cmd/brew-setup-nginx-conf.rb
Something surprising was pointed out to me recently: ports under 1024 are no longer privileged as of macOS 10.14, which means non-root processes can now bind to them. I tested and, in fact, this is true.
This means we no longer need `launch_socket_server` sitting in between Nginx and port 80. We can allow Nginx to bind to those ports directly. Removing one extra tool in the chain is a net benefit to us, and makes things that much simpler!
=> setup-nginx-conf: run nginx on 80/443

cmd/brew-upgrade-mysql
- This was reporting: `Warning: Calling `brew list` to only list formulae is deprecated! Use `brew list --formula` instead.`.
- I originally saw this in github/github `./script/bootstrap` output and tracked it down to here. I don't know how to make `github/github` know that this has changed, but I know from experience that this will fix the error message once it has the newer version.
Before:
```shell
issyl0 at cetus in /usr/local/Homebrew/Library/Taps/github/homebrew-bootstrap on master
❯ brew upgrade-mysql
Checking that MySQL is up to date.
Error: Calling `brew list` to only list formulae is deprecated! Use `brew list --formula` instead.
Installing new version of MySQL...
Warning: mysql@5.7 5.7.32 is already installed and up-to-date
To reinstall 5.7.32, run `brew reinstall mysql@5.7` …
```
=> brew-upgrade-mysql: Fix `brew list` deprecation

Formula/elasticsearch@1.7.rb, Formula/elasticsearch@2.4.rb, Formula/hadoop@2.rb, Formula/hive@2.rb
`depends_on :java` was deprecated in https://github.com/Homebrew/brew/pull/9209.
Ran `brew install` and `brew test` for these all locally and they worked as expected.
=> Use openjdk@8

cmd/brew-upgrade-mysql
- remove installation logic entirely; this is handled more robustly and quickly by `brew bundle`
- remove unused stop logic
- print consistent restart messaging
- output version that we've setup
=> brew-upgrade-mysql: improve performance.

cmd/brew-bootstrap-jenv-java, cmd/brew-bootstrap-nodenv-node, cmd/brew-bootstrap-rbenv-ruby, cmd/brew-report-issue.rb, cmd/brew-setup-nginx-conf.rb, cmd/brew-upgrade-mysql, cmd/brew-vendor-gem
`brew --help` will read from `#:` formatted strings so add/fix these to improve the built-in documentation.
=> Fix --help flag usage

cmd/brew-setup-nginx-conf.rb
The launchdns brew install changed the default resolver from .dev to .localhost, so this updates the log messages around installing it to reflect that
Homebrew/homebrew-core#18365
Homebrew/homebrew-core@9203fb7
=> Update logs to reflect new launchdns default TLD

README.md, cmd/brew-macos-vscode-codespaces
As [reported in Slack](https://github.slack.com/archives/C01S7MANE30/p1621283162156700?thread_ts=1621281287.152600&cid=C01S7MANE30)
Currently the script fails if VS Code is already installed:
```
❯ brew macos-vscode-codespaces
Using launchdns
==> Downloading https://update.code.visualstudio.com/1.56.2/darwin/stable
==> Downloading from https://az764295.vo.msecnd.net/stable/054a9295330880ed74ceaedda236253b4f39a335/VSCode-darwin.zip
==> Installing Cask visual-studio-code
Error: It seems there is already an App at '/Applications/Visual Studio Code.app'.
==> Purging files for version 1.56.2 of Cask visual-studio-code
Installing visual-studio-code has failed!
Homebrew Bundle failed! 1 Brewfile dependency failed to install.
```
But that's really ok, just keep moving along.
=> [Codespaces] Don't fail if VS Code is already installed

cmd/brew-macos-vscode-codespaces
Only one currently but make it easy to add more in future.
=> brew-macos-vscode-codespaces: install VSCode extensions.

cmd/brew-macos-vscode-codespaces
Came here to make the script play a bit nicer on M1, but found a couple of unrelated bugs in the process, so there are two commits here. This is my first PR in this repo so please let me know if I'm doing anything wrong. 😁 
Not fixed in this commit: the fact that `launchdns` currently doesn't install on M1 due to:
```
Error: launchdns: no bottle available!
```
I just installed it from source instead:
```sh
brew install --build-from-source launchdns
```
---
I have my Homebrew files in `/opt/homebrew` because I'm running on an M1, but the script is hard-coded to assume `/usr/local`. As such, the script tries to set the symlink from `/usr/local/etc/resolver` to `/etc/resolver`, and it ends up being a non-existent source.
The fix is to use `$HOMEBREW_PREFIX` if set, and fallback to …
=> Fix M1 issue and a couple of bugs in brew-macos-vscode-codespaces
